
version: "3"

services:
  api:
    build:
      image: redis
    networks:
      api-network:
        aliases:
          - api-net
  nginx:
    build:
      image: nginx 
    ports:
      - "80:80"
      - "443:443"
    networks:
      api-network:
        aliases:
          - nginx-net
    depends_on:
      - api

networks:
  api-network:
