
version: "3"

services:
  mongo:
     image: mongo:4.4.6
     container_name: mongodb
     ports:
      - 27017:27017
     environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:Switch@123
   mongo-express:
     image: mongo-express:0.54.0
     depends_on:
      - mongodb
     container_name: mongo-express
     ports:
      - 8081:8081
     environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD:Switch@123
      - ME_CONFIG_MONGODB_SERVER=mongodb
